/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be in your git ignore file.
// It is auto-generated by Expo and needed by TypeScript to understand the
// Expo Router types. Remove it from .gitignore if you need to inspect it.
