// Algeria — 58 wilayas with their communes (daïras merged into flat commune lists).
// Names in French (Latin) as commonly used in administration. Arabic label provided for UI where useful.
// Source: official ONS / MICL commune list (2020 reform, 58 wilayas).

export interface Wilaya {
  code: string;      // "01".."58"
  name: string;      // French name
  nameAr: string;    // Arabic name
  communes: string[];
}

export const ALGERIA_WILAYAS: Wilaya[] = [
  { code: '01', name: 'Adrar', nameAr: 'أدرار', communes: ['Adrar','Reggane','In Zghmir','Tit','Ksar Kaddour','Tsabit','Timimoun','Ouled Saïd','Zaouiet Kounta','Aoulef','Timokten','Tamest','Charouine','Fenoughil','Tinerkouk','Deldoul','Sali','Akabli','Metarfa','Ouled Ahmed Timmi','Bouda','Aougrout','Talmine','Bordj Badji Mokhtar','Sebaa','Ouled Aïssa','Timiaouine'] },
  { code: '02', name: 'Chlef', nameAr: 'الشلف', communes: ['Chlef','Ténès','Benaïria','El Karimia','Tadjena','Taougrit','Béni Haoua','Sobha','Harchoun','Ouled Fares','Sidi Akkacha','Boukadir','Beni Rached','Talassa','Herenfa','Oued Goussine','Dahra','Ouled Abbes','Sendjas','Zeboudja','Oued Sly','Abou El Hassan','El Marsa','Chettia','Sidi Abderrahmane','Moussadek','El Hadjadj','Labiod Medjadja','Oued Fodda','Ouled Ben Abdelkader','Bouzghaia','Aïn Merane','Oum Drou','Breira','Beni Bouattab'] },
  { code: '03', name: 'Laghouat', nameAr: 'الأغواط', communes: ['Laghouat','Ksar El Hirane','Benacer Benchohra','Sidi Makhlouf','Hassi Delaa','Hassi R\'Mel','Aïn Madhi','Tadjmout','Kheneg','Gueltat Sidi Saad','Aïn Sidi Ali','Beidha','Brida','El Ghicha','Hadj Mechri','Sebgag','Taouiala','Tadjrouna','Aflou','El Assafia','Oued Morra','Oued M\'Zi','El Houaita','Sidi Bouzid','El Haouaita'] },
  { code: '04', name: 'Oum El Bouaghi', nameAr: 'أم البواقي', communes: ['Oum El Bouaghi','Aïn Beïda','Aïn M\'lila','Behir Chergui','El Amiria','Sigus','El Belala','Aïn Babouche','Berriche','Ouled Hamla','Dhalaa','Aïn Kercha','Hanchir Toumghani','El Djazia','Aïn Diss','Fkirina','Souk Naamane','Zorg','El Fedjoudj Boughrara Saoudi','Ouled Zouai','Bir Chouhada','Ksar Sbahi','Oued Nini','Meskiana','Aïn Fekroun','Rahia','Aïn Zitoun','Ouled Gacem','El Harmilia'] },
  { code: '05', name: 'Batna', nameAr: 'باتنة', communes: ['Batna','Ghassira','Maafa','Merouana','Seriana','Menaâ','El Madher','Tazoult','N\'Gaous','Guigba','Inoughissen','Ouyoun El Assafir','Djerma','Bitam','Metkaouak','Arris','Kimmel','Tilatou','Aïn Djasser','Ouled Sellam','Tigherghar','Aïn Yagout','Fesdis','Sefiane','Rahbat','Tighanimine','Lemsane','Ksar Bellezma','Seggana','Ichmoul','Foum Toub','Beni Foudhala El Hakania','Oued El Ma','Talkhamt','Bouzina','Chemora','Oued Chaaba','Taxlent','Gosbat','Ouled Aouf','Boumagueur','Barika','Djezzar','Tkout','Aïn Touta','Hidoussa','Teniet El Abed','Oued Taga','Ouled Fadel','Timgad','Ras El Aioun','Chir','Ouled Si Slimane','Zanat El Beida','M\'Doukal','Ouled Ammar','El Hassi','Lazrou','Boumia','Boulhilat','Larbaa','Kasr Bellezma'] },
  { code: '06', name: 'Béjaïa', nameAr: 'بجاية', communes: ['Béjaïa','Amizour','Ferraoun','Taourirt Ighil','Chellata','Tamokra','Timezrit','Souk El Ténine','M\'Cisna','Thinabdher','Tichy','Semaoun','Kendira','Tifra','Ighram','Amalou','Ighil Ali','Ifelain Ilmathen','Toudja','Darguina','Sidi Ayad','Aokas','Beni Djellil','Adekar','Akbou','Seddouk','Tazmalt','Aït R\'zine','Chemini','Souk Oufella','Taskriout','Tibane','Tala Hamza','Barbacha','Beni Ksila','Ouzellaguen','Bouhamza','Beni Melikeche','Sidi Aïch','El Kseur','Melbou','Akfadou','Leflaye','Kherrata','Dra El Caïd','Tamridjet','Aït Smail','Boukhelifa','Tizi N\'Berber','Beni Maouche','Oued Ghir','Boudjellil'] },
  { code: '07', name: 'Biskra', nameAr: 'بسكرة', communes: ['Biskra','Oumache','Branis','Chetma','Ouled Djellal','Ras El Miaad','Besbes','Sidi Khaled','Doucen','Ech Chaïba','Sidi Okba','Mchouneche','El Haouch','Aïn Naga','Zeribet El Oued','El Feidh','El Kantara','Ain Zaatout','El Outaya','Djemorah','Tolga','Lioua','Lichana','Ourlal','M\'Lili','Foughala','Bordj Ben Azzouz','Meziraa','Bouchagroun','Mekhadma','El Ghrous','El Hadjeb','Khanguet Sidi Nadji'] },
  { code: '08', name: 'Béchar', nameAr: 'بشار', communes: ['Béchar','Erg Ferradj','Ouled Khoudir','Meridja','Timoudi','Lahmar','Beni Abbes','Beni Ikhlef','Mechraa Houari Boumedienne','Kenedsa','Igli','Tabelbala','Taghit','El Ouata','Ksabi','Tamtert','Boukais','Mogheul','Abadla','Kerzaz','Ouled Ali','Beni Ounif','Tamtert','Lahmar'] },
  { code: '09', name: 'Blida', nameAr: 'البليدة', communes: ['Blida','Chebli','Bouinan','Oued El Alleug','Ouled Yaïch','Chréa','El Affroun','Chiffa','Hammam Melouane','Ben Khelil','Soumaa','Mouzaia','Souhane','Meftah','Ouled Selama','Boufarik','Larbaa','Oued Djer','Beni Tamou','Bouarfa','Beni Mered','Bougara','Guerrouaou','Aïn Romana','Djebabra','Beni Merad'] },
  { code: '10', name: 'Bouira', nameAr: 'البويرة', communes: ['Bouira','Asnam','Bordj Oukhriss','El Adjiba','El Hachimia','Aomar','Chorfa','Bechloul','Boukram','Kadiria','Hanif','Dirah','Aït Laaziz','Taghzout','Raouraoua','Mezdour','Haïzer','Lakhdaria','Maala','El Asnam','Guerrouma','Souk El Khemis','Kadiria','Dechmia','Ridane','Bouderbala','Zbarbar','Ahl El Ksar','Bouaklane','El Khabouzia','Aïn Turk','Saharidj','Dirah','Bir Ghbalou','Mchedallah','Sour El Ghozlane','Taguedit','Ath Mansour','El Mokrani','Oued El Berdi','Ahnif'] },
  { code: '11', name: 'Tamanrasset', nameAr: 'تمنراست', communes: ['Tamanrasset','Abalessa','In Ghar','In Guezzam','Idles','Tazrouk','Foggaret Ezzaouia','In Salah','In Amguel','Tinzaouatine'] },
  { code: '12', name: 'Tébessa', nameAr: 'تبسة', communes: ['Tébessa','Bir El Ater','Cheria','Stah Guentis','El Aouinet','Lahouidjbet','Safsaf El Ouesra','Hammamet','Negrine','Bir Mokkadem','El Kouif','Morsott','El Ogla','Bir Dheheb','El Ogla El Malha','Gorriguer','Bekkaria','Boukhadra','Ouenza','El Ma El Abiodh','Ferkane','Aïn Zerga','El Meridj','Boulhaf Dyr','Bedjene','Thlidjene','Oum Ali','Tlidjene','Saf Saf El Ouesra'] },
  { code: '13', name: 'Tlemcen', nameAr: 'تلمسان', communes: ['Tlemcen','Beni Mester','Aïn Tallout','Remchi','El Fehoul','Sabra','Ghazaouet','Souani','Djebala','El Gor','Oued Chouly','Aïn Fezza','Ouled Mimoun','Amieur','Aïn Youcef','Zenata','Beni Snous','Bab El Assa','Dar Yaghmouracen','Fellaoucene','Azails','Sebbaa Chioukh','Terni Beni Hediel','Bensekrane','Aïn Nehala','Hennaya','Maghnia','Hammam Boughrara','Souahlia','Msirda Fouaga','Aïn Fetah','El Aricha','Souk Thlata','Sidi Abdelli','Sebdou','Beni Ouarsous','Sidi Medjahed','Beni Boussaid','Marsa Ben M\'Hidi','Nedroma','Sidi Djillali','Beni Bahdel','El Bouihi','Honaine','Tianet','Ouled Riyah','Bouhlou','Béni Semiel','Aïn Kebira'] },
  { code: '14', name: 'Tiaret', nameAr: 'تيارت', communes: ['Tiaret','Medroussa','Aïn Bouchekif','Sidi Ali Mellal','Aïn Zarit','Aïn Dheb','Sidi Bakhti','Medrissa','Zmalet El Emir Abdelkader','Madna','Sebt','Mellakou','Dahmouni','Rahouia','Mahdia','Sougueur','Si Abdelghani','Aïn Deheb','Sidi Abderrahmane','Nadorah','Tousnina','Frenda','Takhemaret','Sebaine','Tagdemt','Oued Lilli','Mechraa Safa','Hamadia','Chehaima','Takhmaret','Sidi Hosni','Djillali Ben Amar','Sebaine','Tidda','Guertoufa','Sidi Abdelaziz','Serghine','Bougara','Faidja','Tiaret','Oued Lili','Mechraâ Safa','Hamadia','Chehaïma','Takhemaret','Sidi Hosni','Djillali Ben Amar','Sebaïne','Tidda','Guertoufa','Sidi Abdelaziz','Serguine','Bougara','Faïdja'] },
  { code: '15', name: 'Tizi Ouzou', nameAr: 'تيزي وزو', communes: ['Tizi Ouzou','Aïn El Hammam','Akbil','Freha','Souamaa','Mechtras','Irdjen','Timizart','Makouda','Draâ El Mizan','Tizi Gheniff','Bounouh','Aït Chafâa','Frikat','Beni Aïssi','Beni Zmenzer','Iferhounène','Azazga','Iloula Oumalou','Yakouren','Larbaâ Nath Irathen','Tizi Rached','Zekri','Draâ Ben Khedda','Ouacif','Idjeur','Mekla','Tizi N\'Thlata','Beni Ziki','Draâ El Mizan','Boghni','Ifigha','Aït Aggouacha','Bouzeguène','Aït Yahia','Aït Mahmoud','Maâtkas','Aït Boumehdi','Abi Youcef','Beni Douala','Illilten','Bouzeguène','Aït Yahia Moussa','Yatafen','Beni Yenni','Aghrib','Iflissen','Boudjima','Azeffoun','Tigzirt','Aït Aïssa Mimoun','Ouaguenoun','Nouvelle Medina','Tadmaït','Boghni','Mizrana','Imsouhal','Tirmitine','Akerrou','Aïn Zaouia','Aghni Goughran','Yakouren','Agouni Gueghrane','Mekla','Iboudraren'] },
  { code: '16', name: 'Alger', nameAr: 'الجزائر', communes: ['Alger Centre','Sidi M\'Hamed','El Madania','Hamma El Annasser','Bab El Oued','Bologhine','Casbah','Oued Koriche','Bir Mourad Raïs','El Biar','Bouzareah','Birkhadem','El Harrach','Baraki','Oued Smar','Bourouba','Hussein Dey','Kouba','Bachdjerrah','Dar El Beïda','Bab Ezzouar','Ben Aknoun','Dely Ibrahim','El Hammamet','Raïs Hamidou','Djasr Kasentina','El Mouradia','Hydra','Mohammadia','Bordj El Kiffan','El Magharia','Beni Messous','Les Eucalyptus','Birtouta','Tessala El Merdja','Ouled Chebel','Sidi Moussa','Aïn Taya','Bordj El Bahri','Marsa','Haraoua','Rouiba','Reghaïa','Aïn Benian','Staoueli','Zeralda','Mahelma','Rahmania','Souidania','Cheraga','Ouled Fayet','El Achour','Draria','Douera','Baba Hassen','Khraicia','Saoula'] },
  { code: '17', name: 'Djelfa', nameAr: 'الجلفة', communes: ['Djelfa','Moudjebara','El Guedid','Hassi Bahbah','Aïn Maabed','Sed Rahal','Faidh El Botma','Birine','Bouira Lahdab','Zaccar','El Khemis','Sidi Baizid','Mliliha','El Idrissia','Douis','Hassi El Euch','Messaad','Guettara','Sidi Ladjel','Had Sahary','Guernini','Selmana','Aïn Chouhada','Oum Laadham','Dar Chioukh','Charef','Beni Yagoub','Zaafrane','Deldoul','Aïn El Ibel','Aïn Oussera','Benhar','Hassi Fedoul','Amourah','Aïn Fekka','Tadmit'] },
  { code: '18', name: 'Jijel', nameAr: 'جيجل', communes: ['Jijel','Erraguene','El Aouana','Ziama Mansouriah','Taher','Emir Abdelkader','Chekfa','Chahna','El Milia','Sidi Maarouf','Settara','El Ancer','Sidi Abdelaziz','Kaous','Ghebala','Bouraoui Belhadef','Djimla','Selma Benziada','Boussif Ouled Askeur','El Kennar Nouchfi','Ouled Rabah','Ouadjana','Texenna','Djemaa Beni Habibi','Bordj Tahar','Ouled Yahia Khedrouch','Boudria Beni Yadjis','Kemir Oued Adjoul','Rabta Guerrouch'] },
  { code: '19', name: 'Sétif', nameAr: 'سطيف', communes: ['Sétif','Aïn El Kebira','Beni Aziz','Ouled Sidi Ahmed','Boutaleb','Aïn Roua','Draa Kebila','Bir Haddada','Serdj El Ghoul','Hammam Sokhna','Aïn Lahdjar','Ouled Tebben','Bouandas','Bazer Sakhra','Hammam Guergour','Salah Bey','Aïn Arnat','Amoucha','Aïn Oulmene','Beidha Bordj','Bougaa','Beni Ouartilane','Rosfa','Ouled Addouane','Belaa','Aïn Abessa','Dehamcha','Babor','Guidjel','Aïn Azel','Aïn El Hadjar','Bir El Arch','Beni Hocine','Aït Naoual Mezada','Ouricia','Tizi N\'Bechar','Guellal','Aïn Sebt','Hammam Essoukhna','El Eulma','Djemila','Beni Fouda','Tachouda','Beni Mouhli','Oued El Barred','Aïn Legradj','Tala Ifacene','Bousselam','El Ouricia','Taya','Mezloug','Kasr El Abtal','Beni Chebana','Ouled Si Ahmed','Harbil','Aïn Oulmene','Guenzet','Talaifacene','Bir Aassa','Beni Yaghia','Ouled Si Ahmed'] },
  { code: '20', name: 'Saïda', nameAr: 'سعيدة', communes: ['Saïda','Doui Thabet','Aïn El Hadjar','Ouled Khaled','Moulay Larbi','Youb','Hounet','Sidi Amar','Sidi Boubekeur','El Hassasna','Maamora','Sidi Ahmed','Aïn Sekhouna','Ouled Brahim','Tircine','Aïn Soltane'] },
  { code: '21', name: 'Skikda', nameAr: 'سكيكدة', communes: ['Skikda','Aïn Zouit','El Hadaïek','Filfila','Hamadi Krouma','El Marsa','Kerkera','Aïn Kechra','Oum Toub','Bein El Ouiden','Ramdane Djamel','Beni Oulbane','Aïn Bouziane','Ouldja Boulbalout','Kanoua','El Ghedir','Bouchtata','Ouled Attia','Sidi Mezghiche','Djendel Saadi Mohamed','Ouled Hbaba','Sidi Mezghiche','Es Sebt','Collo','Beni Zid','Kheneg Mayoum','Bekkouche Lakhdar','Azzaba','Djendel','Sidi Mezghiche','Tamalous','Aïn Cherchar','Zitouna','Zerdazas','Ouled Zouaï','El Harrouch','Emdjez Edchich','Beni Bechir','Salah Bouchaour','Tala Ifsar','Emdjez Edchich'] },
  { code: '22', name: 'Sidi Bel Abbès', nameAr: 'سيدي بلعباس', communes: ['Sidi Bel Abbès','Tessala','Sidi Brahim','Mostefa Ben Brahim','Telagh','Mezaourou','Boukhanefis','Sidi Ali Benyoub','Chetouane Belaila','Sfisef','Aïn Thrid','Makedra','Tenira','Moulay Slissen','El Hacaiba','Hassi Zehana','Tabia','Merine','Oued Taourira','Dhaya','Zerouala','Lamtar','Tafissour','Amarnas','Tilmouni','Sidi Lahcene','Aïn Adden','Oued Sebaa','Mcid','Hassi Dahou','Aïn El Berd','Badredine El Mokrani','Marhoum','Taoudmout','Oued Sefioun','Teghalimet','Sidi Chaib','Sidi Dahou Des Zairs','Aïn Tindamine','Benachiba Chelia','Sidi Hamadouche','Tenira','Redjem Demouche','Hassi Dahou','Ras El Ma','Sidi Yacoub','Sidi Khaled','Bir El Hammam'] },
  { code: '23', name: 'Annaba', nameAr: 'عنابة', communes: ['Annaba','Berrahal','El Hadjar','Eulma','El Bouni','Oued El Aneb','Cheurfa','Seraïdi','Aïn Berda','Chetaibi','Sidi Amar','Treat'] },
  { code: '24', name: 'Guelma', nameAr: 'قالمة', communes: ['Guelma','Nechmaya','Bouati Mahmoud','Oued Zenati','Tamlouka','Oued Fragha','Aïn Sandel','Ras El Agba','Dahouara','Belkheir','Ben Djarah','Bou Hamdane','Aïn Makhlouf','Aïn Ben Beida','Khezara','Beni Mezline','Bou Hachana','Guelaat Bou Sbaa','Hammam Maskhoutine','El Fedjoudj','Bordj Sabath','Hammam N\'Bails','Aïn Larbi','Medjez Amar','Bouchegouf','Héliopolis','Ras El Agba','Houari Boumedienne','Sellaoua Announa','Medjez Sfa','Khezarah','Nechmaya','Oued Cheham','Roknia','Salah Bouchaour','Tamlouka'] },
  { code: '25', name: 'Constantine', nameAr: 'قسنطينة', communes: ['Constantine','Hamma Bouziane','Didouche Mourad','El Khroub','Aïn Smara','Zighoud Youcef','Beni Hamiden','Ouled Rahmoune','Aïn Abid','Messaoud Boudjeriou','Ibn Ziad'] },
  { code: '26', name: 'Médéa', nameAr: 'المدية', communes: ['Médéa','Ouzera','Tamesguida','El Hamdania','Ouamri','Aïn Boucif','Chelalet El Adhaoura','Aziz','Derrag','El Omaria','Damiat','Si Mahdjoub','Tablat','Baata','Deux Bassins','Beni Slimane','Berrouaghia','Souagui','Bouaiche','Mezerana','Ouled Hellal','Tafraout','Benchicao','Sidi Naamane','Draa Essamar','Ksar El Boukhari','El Azizia','Ouled Deid','Seghouane','Meghraoua','Cheniguel','Aïn Ouksir','Oued Harbil','Djouab','Guelb El Kebir','Sidi Ziane','Tizi Mahdi','Ouled Brahim','Meftaha','Sedraia','Sidi Rabie','Saneg','Hannacha','Tizi N\'dracen','Rebaia','Bouchrahil','Ouled Antar','El Guelb El Kebir','Aïn Boucif'] },
  { code: '27', name: 'Mostaganem', nameAr: 'مستغانم', communes: ['Mostaganem','Sayada','Fornaka','Stidia','Aïn Nouissy','Hassi Maameche','Aïn Tadles','Sour','Oued El Kheir','Sidi Bellater','Khair Eddine','Mazagran','Sidi Ali','Abdelmalek Ramdane','Hadjadj','Nekmaria','Sidi Lakhdar','Achaacha','Khadra','Bouguirat','Sirat','Touahria','El Hassiane','Souaflia','Ouled Boughalem','Ouled Maallah','Mesra','Mansourah','Aïn Sidi Cherif','Tazgait','Safsaf','Kheir Eddine'] },
  { code: '28', name: 'M\'Sila', nameAr: 'المسيلة', communes: ['M\'Sila','Maadid','Hammam Dhalaa','Ouled Derradj','Tarmount','M\'Tarfa','Khoubana','M\'Cif','Chellal','Ouled Madhi','Magra','Berhoum','Ain Khadra','Ouled Addi Guebala','Belaiba','Sidi Aïssa','Aïn El Hadjel','Sidi Hadjeres','Ouanougha','Bou Saâda','Oultene','Zarzour','Ouled Sidi Brahim','Benzouh','Bir Foda','Ain Fares','Sidi M\'Hamed','Ouled Mansour','Tamsa','Ben Srour','Ouled Slimane','El Houamed','El Hamel','Ouled Atia','Souamaa','Aïn El Melh','Medjedel','Slim','Mrissa','Beni Ilmane','Ouled Lamlih','Bou Saâda','Ain Errich','Benzouh','Djebel Messaad','Bir Foda','Ain El Hadjel','Hammam Dhalaa','Sidi Ameur','Tamsa','Ben Srour','Ouled Slimane','El Houamed','El Hamel'] },
  { code: '29', name: 'Mascara', nameAr: 'معسكر', communes: ['Mascara','Bou Hanifia','Tizi','Hacine','Maoussa','Teghennif','El Hachem','Sidi Kada','Zelmata','Oued El Abtal','Aïn Ferah','Ghriss','Froha','Matemore','Makdha','Sidi Boussaid','El Bordj','Ain Fekan','Benian','Khalouia','El Menaouer','Oued Taria','Aouf','Ain Frass','Sehailia','Sidi Abdeldjebar','Sidi Abdelmoumen','El Gaada','El Mamounia','El Keurt','Mohammadia','Sig','Alaïmia','El Gherdjoum','Chorfa','Ras El Ain Amirouche','Gharrous','Gherdjoum','Nesmot','Guetena','Ain Fares','Froha','Hachem','Sig','Bouhanifia','Aïn Fares','Tighennif'] },
  { code: '30', name: 'Ouargla', nameAr: 'ورقلة', communes: ['Ouargla','Aïn Beida','Rouissat','Sidi Khouiled','Hassi Ben Abdellah','El Borma','Touggourt','Nezla','Zaouia El Abidia','Tebesbest','Sidi Slimane','Megarine','Temacine','Blidet Amor','Taibet','M\'Naguer','Benaceur','El Hadjira','El Allia','Taibet','Hassi Messaoud','N\'Goussa','Balidat Ameur','Mégarine'] },
  { code: '31', name: 'Oran', nameAr: 'وهران', communes: ['Oran','Gdyel','Bir El Djir','Hassi Bounif','Es Senia','Arzew','Bethioua','Marsat El Hadjadj','Aïn Turk','El Ançor','Oued Tlelat','Tafraoui','Sidi Chami','Boufatis','Mers El Kebir','Bousfer','El Kerma','El Braya','Hassi Ben Okba','Ben Freha','Hassi Mefsoukh','Sidi Ben Yebka','Messerghin','Boutlelis','Aïn Biya','Hassi Bounif','Sidi El Bachir','Sidi El Houari'] },
  { code: '32', name: 'El Bayadh', nameAr: 'البيض', communes: ['El Bayadh','Rogassa','Stitten','Brezina','Ghassoul','Boualem','El Abiodh Sidi Cheikh','Bougtoub','El Kheiter','Kef El Ahmar','El Bnoud','Cheguig','Sidi Ameur','Sidi Slimane','Tousmouline','Sidi Taïfour','Arbaouat','Krakda','Mehara','El Mehara','Chellala','Boussemghoun'] },
  { code: '33', name: 'Illizi', nameAr: 'إيليزي', communes: ['Illizi','Djanet','Debdeb','Bordj Omar Driss','In Amenas','Bordj El Haouasse'] },
  { code: '34', name: 'Bordj Bou Arreridj', nameAr: 'برج بوعريريج', communes: ['Bordj Bou Arreridj','Ras El Oued','Bordj Zemoura','Mansoura','El Mhir','Ben Daoud','El Achir','Ain Taghrout','Bordj Ghedir','Bordj Zemmoura','Djaafra','Tafreg','Colla','Tixter','El Hamadia','Belimour','Medjana','Teniet En Nasr','Rabta','Haraza','Khelil','Taglait','El Main','Ouled Dahmane','Hasnaoua','Khellil','El Anseur','Ouled Braham','Ghilassa','Sidi Embarek','El Yachir','Ouled Sidi Brahim'] },
  { code: '35', name: 'Boumerdès', nameAr: 'بومرداس', communes: ['Boumerdès','Boudouaou','Afir','Bordj Menaïel','Baghlia','Sidi Daoud','Naciria','Djinet','Isser','Zemmouri','Si Mustapha','Tidjelabine','Chabet El Ameur','Thenia','Timezrit','Corso','Ouled Moussa','Larbatache','Bouzegza Keddara','Taourga','Ouled Aissa','Ben Choud','Dellys','Ammal','Beni Amrane','Souk El Had','Boudouaou El Bahri','Ouled Hedadj','Leghata','Hammedi','Khemis El Khechna'] },
  { code: '36', name: 'El Tarf', nameAr: 'الطارف', communes: ['El Tarf','Bouhadjar','Ben M\'Hidi','Bougous','El Kala','Aïn El Assel','El Aioun','Bouteldja','Souarekh','Berrihane','Lac des Oiseaux','Chefia','Dréan','Chihani','Chebaita Mokhtar','Besbes','Asfour','Echatt','Zerizer','Zitouna','Ain Kerma','Raml Souk','Hammam Beni Salah','El Chatt'] },
  { code: '37', name: 'Tindouf', nameAr: 'تندوف', communes: ['Tindouf','Oum El Assel'] },
  { code: '38', name: 'Tissemsilt', nameAr: 'تيسمسيلت', communes: ['Tissemsilt','Bordj Bou Naama','Theniet El Had','Lazharia','Beni Chaib','Lardjem','Melaab','Sidi Lantri','Bordj El Emir Abdelkader','Layoune','Khemisti','Ouled Bessem','Ammari','Youssoufia','Sidi Abed','Tamalaht','Sidi Boutouchent','Larbaâ','Maacem','Sidi Slimane','Boucaid','Beni Lahcene','Sidi Ouadah'] },
  { code: '39', name: 'El Oued', nameAr: 'الوادي', communes: ['El Oued','Robbah','Oued El Alenda','Bayadha','Nakhla','Guemar','Kouinine','Reguiba','Hamraia','Taghzout','Debila','Hassani Abdelkrim','Hassi Khalifa','Taleb Larbi','Douar El Ma','Sidi Aoun','Trifaoui','Magrane','Beni Guecha','Ourmes','Mih Ouansa','Still','El Ogla','Mrara','Sidi Khellil','Tendla','El Besbes','Djamaa','M\'Rara','Sidi Amrane','Menguellet','Oum Touyour','El M\'Ghair','Oum Tiour','Sidi Khellil','Tendla','Mrara','Still','Beni Guecha','El Ogla','Magrane','Mih Ouansa','Ourmes','Taleb Larbi','Hassi Khalifa','Reguiba','Trifaoui'] },
  { code: '40', name: 'Khenchela', nameAr: 'خنشلة', communes: ['Khenchela','Mtoussa','Kais','Baghai','El Hamma','Ain Touila','Taouzianat','Bouhmama','El Oueldja','Ouled Rechache','El Mahmel','Chechar','Djellal','Babar','Tamza','Ensigha','Ouled Rechache','Msara','Chelia','Remila','N\'Sigha','Yabous'] },
  { code: '41', name: 'Souk Ahras', nameAr: 'سوق أهراس', communes: ['Souk Ahras','Sedrata','Hanancha','Mechroha','Ouled Driss','Tiffech','Zaarouria','Taoura','Drea','Haddada','Khedara','Merahna','Ouled Moumen','Bir Bouhouche','M\'Daourouch','Oum El Adhaim','Aïn Zana','Aïn Soltane','Ouillen','Sidi Fredj','Safel El Ouiden','Ragouba','Khemissa','Mdaourouch','Oued Keberit','Terraguelt','Machroha','Henancha'] },
  { code: '42', name: 'Tipaza', nameAr: 'تيبازة', communes: ['Tipaza','Menaceur','Larhat','Douaouda','Bourkika','Khemisti','Aghbal','Hadjout','Sidi Amar','Gouraya','Nador','Cherchell','Damous','Meurad','Fouka','Bou Ismail','Ahmar El Aïn','Bou Haroun','Sidi Ghiles','Messelmoun','Sidi Rached','Kolea','Attatba','Sidi Semiane','Beni Milleuk','Hadjeret Ennous','Chaiba','Tipaza','Ain Tagourait'] },
  { code: '43', name: 'Mila', nameAr: 'ميلة', communes: ['Mila','Ferdjioua','Chelghoum Laïd','Oued Athmenia','Ahmed Rachedi','Ouled Khalouf','Tiberguent','Bouhatem','Rouached','Tessadane Haddada','Grarem Gouga','Sidi Merouane','Tassadane Haddada','Derradji Bousselah','Minar Zarza','Amira Arras','Terrai Bainen','Hamala','Ain Tine','Yahia Beniguecha','Zeghaia','Elayadi Barbes','Tadjenanet','Benyahia Abderrahmane','Oued Seguen','Mechira','Sidi Khelifa','El Mechira','Oued Endja','Ain Beida Harriche','Ouled Addouane','Bouhatem','Raddas Slimane','Ahmed Rachdi','El Aayadi'] },
  { code: '44', name: 'Aïn Defla', nameAr: 'عين الدفلى', communes: ['Aïn Defla','Miliana','Boumedfaa','Khemis Miliana','Hammam Righa','Arib','Djelida','El Attaf','El Abadia','Bourached','Aïn Soltane','Tarik Ibn Ziad','Rouina','Zeddine','El Hassania','Bir Ould Khelifa','Ain Torki','Tiberkanine','Bathia','El Amra','Ain Lechiakh','Oued Chorfa','Ain Bouyahia','Djemaa Ouled Chikh','Belaas','Ben Allal','Djendel','Sidi Lakhdar','Aïn Benian','Tacheta Zougagha','Bordj Emir Khaled','Ain Defla','Ain Soltane','El Maine','Mekhatria','Oued Djemaa','Bir Ould Khelifa','Arib'] },
  { code: '45', name: 'Naâma', nameAr: 'النعامة', communes: ['Naâma','Mechria','Aïn Sefra','Tiout','Sfissifa','Moghrar','Assela','Djenien Bourezg','Aïn Ben Khelil','Makman Ben Amer','Kasdir','El Biodh'] },
  { code: '46', name: 'Aïn Témouchent', nameAr: 'عين تموشنت', communes: ['Aïn Témouchent','Chaabet El Ham','Aïn Kihal','Hammam Bou Hadjar','Bou Zedjar','Oued Berkeche','Aghlal','Terga','Ouled Kihal','Aïn Tolba','El Amria','Hassi El Ghella','Hassasna','Chentouf','Sidi Ben Adda','Aoubellil','El Malah','Sidi Ouriache','El Emir Abdelkader','Tamzoura','Chentouf','Oulhaça El Gheraba','Sidi Boumediene','Beni Saf','Sidi Safi','Oued Sabah','Aïn El Arbaa','Ouled Boudjemaa'] },
  { code: '47', name: 'Ghardaïa', nameAr: 'غرداية', communes: ['Ghardaïa','El Meniaa','Dhayet Bendhahoua','Berriane','Metlili','El Guerrara','El Atteuf','Zelfana','Sebseb','Bounoura','Hassi El Gara','Hassi Fehal','Mansoura'] },
  { code: '48', name: 'Relizane', nameAr: 'غليزان', communes: ['Relizane','Oued Rhiou','Belaassel Bouzegza','Sidi Saada','Ouled Aiche','Sidi Lazreg','El Hamadna','Sidi M\'Hamed Ben Ali','Mediouna','Sidi Khettab','Ammi Moussa','Zemmoura','Beni Dergoun','Djidiouia','El Guettar','Hamri','El Matmar','Sidi M\'Hamed Ben Aouda','Ain Tarek','Oued Essalem','Ouarizane','Mazouna','Kalaa','Ain Rahma','Yellel','Oued El Djemaa','Ramka','Mendes','Lahlef','Beni Zentis','Souk El Had','El Hassi','Had Echkalla','Ain Reihane','Bendaoud','El Ouldja'] },
  { code: '49', name: 'Timimoun', nameAr: 'تيميمون', communes: ['Timimoun','Aougrout','Ouled Aïssa','Charouine','Ouled Saïd','Talmine','Ksar Kaddour','Tinerkouk','Deldoul','Metarfa'] },
  { code: '50', name: 'Bordj Badji Mokhtar', nameAr: 'برج باجي مختار', communes: ['Bordj Badji Mokhtar','Timiaouine'] },
  { code: '51', name: 'Ouled Djellal', nameAr: 'أولاد جلال', communes: ['Ouled Djellal','Ras El Miaad','Besbes','Sidi Khaled','Doucen','Ech Chaïba'] },
  { code: '52', name: 'Béni Abbès', nameAr: 'بني عباس', communes: ['Béni Abbès','El Ouata','Kerzaz','Ksabi','Tamtert','Igli','Tabelbala','Ouled Khoudir'] },
  { code: '53', name: 'In Salah', nameAr: 'عين صالح', communes: ['In Salah','Foggaret Ezzaouia','In Ghar'] },
  { code: '54', name: 'In Guezzam', nameAr: 'عين قزام', communes: ['In Guezzam','Tinzaouatine'] },
  { code: '55', name: 'Touggourt', nameAr: 'تقرت', communes: ['Touggourt','Nezla','Zaouia El Abidia','Tebesbest','Sidi Slimane','Megarine','Temacine','Blidet Amor','Taibet','M\'Naguer','Benaceur','El Hadjira'] },
  { code: '56', name: 'Djanet', nameAr: 'جانت', communes: ['Djanet','Bordj El Haouasse'] },
  { code: '57', name: 'El M\'Ghair', nameAr: 'المغير', communes: ['El M\'Ghair','Still','Djamaa','Sidi Amrane','Mrara','Oum Touyour','Tendla','Sidi Khellil'] },
  { code: '58', name: 'El Meniaa', nameAr: 'المنيعة', communes: ['El Meniaa','Hassi El Gara','Hassi Fehal'] },
];

export const BLOOD_TYPES = ['A+','A-','B+','B-','AB+','AB-','O+','O-'] as const;
export const GENDERS = ['male','female'] as const;

export function getWilayaByCode(code: string): Wilaya | undefined {
  return ALGERIA_WILAYAS.find(w => w.code === code);
}

export function getCommunes(code: string): string[] {
  return getWilayaByCode(code)?.communes ?? [];
}
