import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — Qflo',
  description: 'How Qflo collects, uses, stores, and protects your personal data.',
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16 text-foreground">
      <h1 className="mb-2 text-3xl font-bold">Privacy Policy</h1>
      <p className="mb-10 text-sm text-muted-foreground">Effective date: 27 March 2026 · Last updated: 27 March 2026</p>

      <div className="space-y-8 text-[15px] leading-relaxed text-muted-foreground">
        {/* ── Introduction ── */}
        <section>
          <p>
            Qflo (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) operates the queue management platform
            available at <strong>qflo.net</strong>, the Qflo mobile applications, the Qflo Station
            desktop application, and related kiosk interfaces (collectively, the &quot;Service&quot;).
            This Privacy Policy explains what personal data we collect, why we collect it, how we use
            and protect it, and what rights you have regarding your data.
          </p>
          <p className="mt-3">
            By using the Service you acknowledge that you have read and understood this Privacy Policy.
            If you are a business using Qflo to manage queues (&quot;Organization&quot;), you are the
            data controller for the customer data processed through your queues; Qflo acts as a data
            processor on your behalf.
          </p>
        </section>

        {/* ── 1. Data We Collect ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">1. Data We Collect</h2>

          <h3 className="mb-1 mt-4 font-semibold text-foreground">1.1 Data provided by customers (visitors)</h3>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li><strong>Name</strong> — if entered at the kiosk or when joining a queue online (optional unless required by the business).</li>
            <li><strong>Phone number</strong> — if entered for WhatsApp or SMS notifications (optional).</li>
            <li><strong>Email address</strong> — if provided for appointment booking or notifications.</li>
            <li><strong>Appointment details</strong> — date, time, service selected, and any notes you provide when booking.</li>
          </ul>

          <h3 className="mb-1 mt-4 font-semibold text-foreground">1.2 Data generated by the Service</h3>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li><strong>Ticket data</strong> — ticket number, queue position, status (waiting, called, served, no-show), timestamps, assigned desk, and estimated wait time.</li>
            <li><strong>Notification records</strong> — delivery status of WhatsApp, Messenger, and push notifications sent to you.</li>
            <li><strong>QR tokens</strong> — unique tokens embedded in QR codes for ticket tracking. These do not contain personal information.</li>
            <li><strong>Session identifiers</strong> — for WhatsApp and Messenger conversations linked to your ticket.</li>
          </ul>

          <h3 className="mb-1 mt-4 font-semibold text-foreground">1.3 Data from business operators (staff)</h3>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li><strong>Account information</strong> — name, email address, and role within the organization.</li>
            <li><strong>Authentication data</strong> — securely hashed passwords or third-party OAuth tokens.</li>
            <li><strong>Activity logs</strong> — actions taken within the dashboard (calling tickets, completing service, etc.) for audit purposes.</li>
          </ul>

          <h3 className="mb-1 mt-4 font-semibold text-foreground">1.4 Automatically collected data</h3>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li><strong>Device and browser information</strong> — browser type, operating system, screen resolution, and language preference.</li>
            <li><strong>IP address</strong> — used for security, rate limiting, and approximate geolocation (country/region level only).</li>
            <li><strong>Cookies</strong> — essential cookies for authentication and session management only. See Section 7.</li>
          </ul>
        </section>

        {/* ── 2. How We Use Your Data ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">2. How We Use Your Data</h2>
          <p>We use the collected data for the following purposes:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li><strong>Queue management</strong> — to issue tickets, track positions, assign desks, and manage the flow of visitors.</li>
            <li><strong>Notifications</strong> — to send real-time updates about your queue status via WhatsApp, Facebook Messenger, push notifications, or on-screen displays.</li>
            <li><strong>Appointment scheduling</strong> — to book, confirm, reschedule, and check in for appointments.</li>
            <li><strong>Analytics and reporting</strong> — to provide businesses with aggregated, anonymized statistics about wait times, service duration, and visitor volume.</li>
            <li><strong>Service improvement</strong> — to monitor performance, fix bugs, and improve the user experience.</li>
            <li><strong>Security</strong> — to prevent fraud, detect abuse, and maintain the integrity of the platform.</li>
          </ul>
          <p className="mt-3">We do <strong>not</strong> use your data for advertising, profiling, or automated decision-making.</p>
        </section>

        {/* ── 3. Messaging & Notifications ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">3. Messaging &amp; Notifications</h2>
          <p>Qflo can send queue updates through the following channels, only when you opt in:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>
              <strong>WhatsApp</strong> — powered by the WhatsApp Business API (operated by Meta Platforms, Inc.).
              When you provide your phone number for WhatsApp alerts, we share it with Meta solely to deliver queue
              notifications. Meta&apos;s own privacy policy applies to WhatsApp message delivery.
            </li>
            <li>
              <strong>Facebook Messenger</strong> — when you interact with our Messenger bot, Meta provides us with
              your Messenger user ID and display name. We use this only to send queue updates. We do not access your
              Facebook profile, friends list, or any other Facebook data.
            </li>
            <li>
              <strong>Push notifications</strong> — sent via web push or mobile push. You can revoke permission at any
              time through your browser or device settings.
            </li>
          </ul>
          <p className="mt-3">
            You can stop receiving messages at any time by not providing your phone number, blocking the WhatsApp
            number, or unsubscribing from the Messenger bot. Notification preferences are per-ticket and are not
            stored beyond the lifecycle of your visit.
          </p>
        </section>

        {/* ── 4. Data Sharing & Third-Party Processors ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">4. Data Sharing &amp; Third-Party Processors</h2>
          <p>We do not sell, rent, or trade your personal data. We share data only with the following service providers who process it on our behalf:</p>
          <table className="mt-3 w-full text-sm">
            <thead>
              <tr className="border-b text-left text-foreground">
                <th className="pb-2 pr-4 font-semibold">Provider</th>
                <th className="pb-2 pr-4 font-semibold">Purpose</th>
                <th className="pb-2 font-semibold">Data shared</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              <tr>
                <td className="py-2 pr-4 align-top font-medium text-foreground">Supabase (AWS)</td>
                <td className="py-2 pr-4 align-top">Database hosting, authentication, real-time subscriptions</td>
                <td className="py-2 align-top">All service data (encrypted at rest and in transit)</td>
              </tr>
              <tr>
                <td className="py-2 pr-4 align-top font-medium text-foreground">Vercel</td>
                <td className="py-2 pr-4 align-top">Web application hosting, edge functions</td>
                <td className="py-2 align-top">HTTP request data, server-side logs</td>
              </tr>
              <tr>
                <td className="py-2 pr-4 align-top font-medium text-foreground">Meta Platforms</td>
                <td className="py-2 pr-4 align-top">WhatsApp Business API, Messenger Platform</td>
                <td className="py-2 align-top">Phone number (WhatsApp), Messenger user ID</td>
              </tr>
              <tr>
                <td className="py-2 pr-4 align-top font-medium text-foreground">GitHub</td>
                <td className="py-2 pr-4 align-top">Desktop app auto-updates</td>
                <td className="py-2 align-top">App version, OS type (no personal data)</td>
              </tr>
            </tbody>
          </table>
          <p className="mt-3">
            The business using Qflo to manage their queues may access the data you provide (name, phone, ticket status)
            through their dashboard. The business is the data controller for this data and their own privacy practices apply.
          </p>
        </section>

        {/* ── 5. Data Retention ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">5. Data Retention</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li><strong>Ticket and visit data</strong> — retained for up to 90 days for reporting purposes, then permanently deleted.</li>
            <li><strong>Appointment data</strong> — retained until 30 days after the appointment date.</li>
            <li><strong>Notification records</strong> — retained for 30 days.</li>
            <li><strong>WhatsApp/Messenger session data</strong> — deleted within 24 hours after the visit is completed or the session expires.</li>
            <li><strong>Staff account data</strong> — retained as long as the account is active. Deleted within 30 days of account closure.</li>
            <li><strong>Anonymous analytics</strong> — aggregated data with no personal identifiers may be retained indefinitely.</li>
          </ul>
        </section>

        {/* ── 6. Data Security ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">6. Data Security</h2>
          <p>We implement appropriate technical and organizational measures to protect your data:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>All data is encrypted in transit (TLS 1.2+) and at rest (AES-256).</li>
            <li>Database access is restricted by row-level security policies.</li>
            <li>Authentication uses industry-standard protocols (bcrypt hashing, JWT tokens).</li>
            <li>Staff access to customer data is limited by role-based permissions.</li>
            <li>We conduct regular security reviews and dependency audits.</li>
          </ul>
          <p className="mt-3">
            No system is 100% secure. If you become aware of any security vulnerability, please contact us
            immediately at <a href="mailto:security@qflo.net" className="text-primary underline">security@qflo.net</a>.
          </p>
        </section>

        {/* ── 7. Cookies ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">7. Cookies</h2>
          <p>Qflo uses only essential cookies:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li><strong>Authentication cookies</strong> — to keep you signed in to the dashboard.</li>
            <li><strong>Language preference</strong> — to remember your selected language (en, fr, ar).</li>
            <li><strong>Session cookies</strong> — for CSRF protection and security.</li>
          </ul>
          <p className="mt-3">We do not use advertising cookies, analytics cookies, or any third-party tracking cookies.</p>
        </section>

        {/* ── 8. Your Rights ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">8. Your Rights</h2>
          <p>Depending on your location, you may have the following rights regarding your personal data:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li><strong>Access</strong> — request a copy of the data we hold about you.</li>
            <li><strong>Rectification</strong> — request correction of inaccurate data.</li>
            <li><strong>Erasure</strong> — request deletion of your data (&quot;right to be forgotten&quot;).</li>
            <li><strong>Portability</strong> — request your data in a machine-readable format.</li>
            <li><strong>Restriction</strong> — request that we limit how we process your data.</li>
            <li><strong>Objection</strong> — object to processing of your data for specific purposes.</li>
            <li><strong>Withdraw consent</strong> — where processing is based on consent, you may withdraw it at any time.</li>
          </ul>
          <p className="mt-3">
            To exercise any of these rights, contact us at{' '}
            <a href="mailto:privacy@qflo.net" className="text-primary underline">privacy@qflo.net</a>.
            We will respond within 30 days.
          </p>
          <p className="mt-2">
            If you are in the European Economic Area (EEA), you also have the right to lodge a complaint with your
            local data protection authority.
          </p>
        </section>

        {/* ── 9. Children's Privacy ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">9. Children&apos;s Privacy</h2>
          <p>
            Qflo is not directed at children under 16. We do not knowingly collect personal data from children.
            If you believe a child has provided us with personal data, please contact us and we will delete it promptly.
          </p>
        </section>

        {/* ── 10. International Data Transfers ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">10. International Data Transfers</h2>
          <p>
            Your data may be processed in countries outside your country of residence, including the United States
            and the European Union, where our infrastructure providers operate. We ensure that appropriate safeguards
            are in place (such as Standard Contractual Clauses) for any cross-border data transfers.
          </p>
        </section>

        {/* ── 11. Changes to This Policy ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">11. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify you of material changes by posting
            the updated policy on this page and updating the &quot;Last updated&quot; date. Continued use of the
            Service after changes constitutes acceptance of the revised policy.
          </p>
        </section>

        {/* ── 12. Contact ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-foreground">12. Contact</h2>
          <p>For privacy-related questions or requests:</p>
          <ul className="mt-2 space-y-1 pl-5">
            <li>Email: <a href="mailto:privacy@qflo.net" className="text-primary underline">privacy@qflo.net</a></li>
            <li>General support: <a href="mailto:support@qflo.net" className="text-primary underline">support@qflo.net</a></li>
          </ul>
        </section>
      </div>
    </div>
  );
}
